[app]
  #app名称
  name = "project-api"
  url = "http://localhost"
  port = ":8080"
  debug = false

[database]
  dirver = "mysql"

[mysql]
  dbname = "@tcp(127.0.0.1:3306)/dbname?charset=utf8"
  username = "root"
  password = "password"
